# Streamlit Secrets for Deployment
# This file contains environment variables for Streamlit Cloud deployment
# DO NOT commit this file to version control - add to .gitignore

# Google Gemini API Key
GOOGLE_API_KEY = "AIzaSyBqBVttvrsnbeYyqDHmn7y3J1y4mXY28v0"

# SerpAPI Key for flight and hotel searches
SERPAPI_API_KEY = "b63f5b418632da472c04d5e858b89f5f3b07c0186c4cc461af6bf712314f30fb"

# Mailgun Configuration (commented out - email functionality disabled)
# MAILGUN_API_KEY = "your_mailgun_api_key_here"